# Generated by Django 4.2.7 on 2023-11-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
