# Generated by Django 4.2.7 on 2023-11-23 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0002_video_title2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title2',
        ),
    ]
