# Generated by Django 5.0.3 on 2024-03-28 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opencv', '0003_remove_video_title2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
