# Generated by Django 5.0.3 on 2024-03-29 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('opencv', '0004_delete_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='Название объекта')),
                ('media_file', models.FileField(upload_to='photos/', verbose_name='Медиа файл объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
            ],
        ),
    ]
