# Generated by Django 5.0.2 on 2024-02-25 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_russian', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='photos/', verbose_name='Файл фотографии объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание объекта')),
            ],
        ),
        migrations.CreateModel(
            name='Researches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название исследования')),
                ('date_collected', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, verbose_name='Описание исследования')),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, verbose_name='Описание технологии')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_classes', to='research.photo')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='research.classes')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='research',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researches', verbose_name='Исследование'),
        ),
        migrations.CreateModel(
            name='ResearchTechnologies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('researches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_classes', to='research.researches')),
                ('technologies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='research.technologies')),
            ],
        ),
    ]
