# Generated by Django 5.0.2 on 2024-02-27 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_object_research'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media_file',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.FileField(upload_to='photos/', verbose_name='Медиа файл объекта')),
                ('description', models.TextField(blank=True, verbose_name='Описание изображения')),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.researches', verbose_name='Исследование')),
            ],
        ),
        migrations.AlterField(
            model_name='photoclass',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detected_classes', to='research.media_file'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
