# Generated by Django 5.0.2 on 2024-02-29 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0003_media_file_alter_photoclass_photo_delete_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Class',
        ),
        migrations.RenameModel(
            old_name='Researches',
            new_name='Research',
        ),
        migrations.RenameModel(
            old_name='ResearchTechnologies',
            new_name='ResearchTechnology',
        ),
        migrations.RenameModel(
            old_name='Technologies',
            new_name='Technology',
        ),
    ]
