# Generated by Django 5.0.2 on 2024-03-08 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_research_technologies'),
    ]

    operations = [
        migrations.AddField(
            model_name='media_file',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Название объекта'),
        ),
    ]
